In [1]:
import numpy as np

In [2]:
list=[1,3,5,7]
list1=[2,4,6,8]
print(list+list1)

[1, 3, 5, 7, 2, 4, 6, 8]


In [7]:
# if a one element in the numpy array is string so all of the numeric values is also converted into String  
a=np.array([1,2,3,4,"ali"])
b=np.array([1,2,3,4,"ali"])
print(a+b)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> None

In [5]:
a=np.array([10,20,30])
b=np.array([10,20,30])
print((a+b)*3)

[ 60 120 180]


In [13]:
# in this numpy array if we made the nested array so the element count must be same that is 2 or 2 in bottom example 
list1=np.array([[20,30],[40,60]])  #in this we created a marix consist of two values
print(list1)
print(type(list1))


[[20 30]
 [40 60]]
<class 'numpy.ndarray'>


In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:4]) # output [2,3,4]
print(arr[:4]) # output [1,2,3,4]
print(arr[5:1]) # output []
print(arr[3:-1]) # output [2,3,4]
print(arr[7:]) # output [2,3,4]

[2 3 4]
[1 2 3 4]
[]
[4 5 6 7 8]
[8 9]


In [32]:
# multiple matrixes examples
arrs=np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(arrs[0:3,1:4])
# short form for silicing
print(arrs[1,2])# this is short method for that kai 1 indicate index value and the number 2 is indicate only value i  want is the second value of secnd matrix that is 5
print(arrs[1,0:2])
print(arrs.astype(str)) # convert the numeric array into String

[[4 6 8]
 [3 5 7]]
5
[1 3]
[['2' '4' '6' '8' '10']
 ['1' '3' '5' '7' '9']]


In [31]:
print(np.shape(arrs)) # shape function determine the rows and columns of arrays output(2,5) that is row is 2 and column is 5
print(np.size(arrs)) #means the total numbers of columns that is 10
print(np.ndim(arrs)) # means how many dimesnion is in array that is 2
print(arrs.dtype) # it describe the datadtype of element store in arrays of numpy

(2, 5)
10
2
int32


In [38]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(np.add(arr1,arr2)) # addition operator is work to add two values
print(np.subtract(arr1,arr2)) # subtract operator is used to subtract two numbers
print(np.multiply(arr1,arr2))
print(np.divide(arr2,arr1))
print(np.power(arr1,arr2))
print(np.sqrt(arr1))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]
[      1     128    6561  262144 9765625]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [47]:
# in order to contencatenate two values in numpy then we used this 
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(np.concatenate([arr1,arr2]))

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr3=np.array([[1,2,3],[4,5,6]])
arr4=np.array([[7,8,9],[10,11,12]])

print(np.concatenate([arr3,arr4],axis=1)) # in this exaple the arr3 get the axis of 

In [2]:
import numpy as np
a=np.array([2,4,5,6,7,8,3,3,2,9,3])
print(np.array_split(a,3))

[array([2, 4, 5, 6]), array([7, 8, 3, 3]), array([2, 9, 3])]


In [6]:
import numpy as np
a=np.array([2,4,5,6,7,8,3,3,2,9,3])
b=np.array_split(a,3) # it is used to break arrays into two parts
print(b[1])

[7 8 3 3]


In [16]:
c=np.array([[20,40],[50,60]])
print(np.append(c,[[70,80],[90,100]]))
print(np.insert(c,1,99))#array,index,value
print(np.delete(c,1))

[ 20  40  50  60  70  80  90 100]
[20 99 40 50 60]
[20 50 60]


In [20]:
# here we can discuss about the filter,sort and search
import numpy as np
arrs=np.array([[5,6,4,3,8,1,9],[6,7,5,1,0,2,3]])
print(np.sort(arrs))
#search
arrays=[1,3,4,5]
search=np.where(arrays == 5)
print(search)

[[1 3 4 5 6 8 9]
 [0 1 2 3 5 6 7]]
(array([], dtype=int64),)


C:\Users\PMLS\AppData\Local\Temp\ipykernel_16020\1147126021.py:7: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  search=np.where(arrays == 5)


In [22]:
#here we discuss about filter
ar=np.array([20,30,40,50])
# fa=[True,False,True,False]
# new=ar[fa]
# print(new)
fa=ar>35
new=ar[fa]
print(new)

[40 50]
